create table public.pipeline_reads (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  pipeline_name text null,
  content json[] null,
  pipeline_id text null,
  issue bigint null default '0'::bigint,
  user_id uuid null,
  constraint popular_pkey primary key (id)
) TABLESPACE pg_default;