-- not used anymore. will delete later

create table public.popular_config (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  subreddits text[] null,
  category text null,
  focus text null,
  source text[] null,
  constraint popular_config_pkey primary key (id)
) TABLESPACE pg_default;